# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x10org.example.pypi\"\x0e\n\x01M\x12\t\n\x01\x61\x18\x01 \x01(\x05')



_M = DESCRIPTOR.message_types_by_name['M']
M = _reflection.GeneratedProtocolMessageType('M', (_message.Message,), {
  'DESCRIPTOR' : _M,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:org.example.pypi.M)
  })
_sym_db.RegisterMessage(M)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _M._serialized_start=34
  _M._serialized_end=48
# @@protoc_insertion_point(module_scope)
